### ISSUE TITLE
Some packages are not loaded correctly when automatically restore is triggered

### ISSUE THREAD

**Issue by KristianMariyanov** [BlazorRepl/BlazorRepl#132]
Steps:
1. Open this snippet https://blazorrepl.com/repl/mvYccSkP00Uto3zT17
2. Click the run button

It throws: 
```
Unhandled exception rendering component: Could not load file or assembly 'Bogus, Version=31.0.3.0, Culture=neutral, PublicKeyToken=fa1bb3f3f218129a' or one of its dependencies.
System.IO.FileNotFoundException: Could not load file or assembly 'Bogus, Version=31.0.3.0, Culture=neutral, PublicKeyToken=fa1bb3f3f218129a' or one of its dependencies.
File name: 'Bogus, Version=31.0.3.0, Culture=neutral, PublicKeyToken=fa1bb3f3f218129a'
   at BlazorRepl.UserComponents.__Main.<UpdateUsers>b__19_0()
   at Microsoft.AspNetCore.Components.WebAssembly.Rendering.NullDispatcher.InvokeAsync(Action workItem)
   at Microsoft.AspNetCore.Components.ComponentBase.InvokeAsync(Action workItem)
   at BlazorRepl.UserComponents.__Main.UpdateUsers()
   at BlazorRepl.UserComponents.__Main.OnInitializedAsync()
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
```

The most probable reason is that the dll is loaded before all bites are uploaded from the repl.

**Comment by KristianMariyanov** [comment]
closes with: https://github.com/BlazorRepl/BlazorRepl/commit/b80a51f91f73e1bc96125f5626c74b0faf87810e
